const { createClient } = supabase;

const supabaseClient = createClient('https://ixhceohsjzdhgokxnfoo.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4aGNlb2hzanpkaGdva3huZm9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NjQyMjcsImV4cCI6MjA2MTA0MDIyN30.Io6Wh8o_uzaToqJqcN2DGExdoV0bvUfiRZA8_Mnq_l4');
